
set(FAITHFUL_DEPS_FOUND ON)

function(lib_found_info libName libraryIncludeDir Library)
    if(${libraryIncludeDir} AND ${Library})
        set(${libName}_FOUND ON PARENT_SCOPE)
        message(STATUS "${libName}: ${${Library}}")
    else()
        set(${libName}_FOUND OFF PARENT_SCOPE)
        set(FAITHFUL_DEPS_FOUND OFF PARENT_SCOPE)
        message(STATUS "${libName}: __not_found__")
    endif()
endfunction()

function(header_found_info libName libraryIncludeDir)
    if(${libraryIncludeDir})
        set(${libName}_FOUND ON PARENT_SCOPE)
        message(STATUS "${libName}: ${${libraryIncludeDir}}")
    else()
        set(${libName}_FOUND OFF PARENT_SCOPE)
        set(FAITHFUL_DEPS_FOUND OFF PARENT_SCOPE)
        message(STATUS "${libName}: __not_found__")
    endif()
endfunction()
