
set(FAITHFUL_DEPS_FOUND ON CACHE BOOL PARENT_SCOPE FORCE)

function(lib_found_info libName libraryIncludeDir Library)
    if (${libraryIncludeDir} AND ${Library})
        set(${libName}_FOUND true PARENT_SCOPE)
        message(STATUS "${libName}: ${${Library}}")
    else()
        set(${libName}_FOUND false PARENT_SCOPE)
        set(FAITHFUL_DEPS_FOUND OFF CACHE BOOL PARENT_SCOPE FORCE)
        message(STATUS "${libName}: __not_found__")
    endif()
endfunction()

function(header_found_info libName libraryIncludeDir)
    if (${libraryIncludeDir})
        set(${libName}_FOUND true PARENT_SCOPE)
        message(STATUS "${libName}: ${${libraryIncludeDir}}")
    else()
        set(${libName}_FOUND false PARENT_SCOPE)
        set(FAITHFUL_DEPS_FOUND OFF CACHE BOOL PARENT_SCOPE FORCE)
        message(STATUS "${libName}: __not_found__")
    endif()
endfunction()
