cmake_minimum_required(VERSION 3.0)

include(${CMAKE_SOURCE_DIR}/cmake/FaithfulFunctions.cmake)

find_path(LIBAVUTIL_INCLUDE_DIR libavutil/avutil.h)
find_library(LIBAVUTIL_LIBRARY avutil)
lib_found_info(LIBAVUTIL LIBAVUTIL_INCLUDE_DIR LIBAVUTIL_LIBRARY)

find_path(LIBAVCODEC_INCLUDE_DIR libavcodec/avcodec.h)
find_library(LIBAVCODEC_LIBRARY avcodec)
lib_found_info(LIBAVCODEC LIBAVCODEC_INCLUDE_DIR LIBAVCODEC_LIBRARY)

find_path(LIBAVFORMAT_INCLUDE_DIR libavformat/avformat.h)
find_library(LIBAVFORMAT_LIBRARY avformat)
lib_found_info(LIBAVFORMAT LIBAVFORMAT_INCLUDE_DIR LIBAVFORMAT_LIBRARY)

mark_as_advanced(
        LIBAVUTIL_INCLUDE_DIR LIBAVUTIL_LIBRARY
        LIBAVCODEC_INCLUDE_DIR LIBAVCODEC_LIBRARY
        LIBAVFORMAT_INCLUDE_DIR LIBAVFORMAT_LIBRARY
)
