
macro(print_system_and_cmake_info)
    message(STATUS "._._._._._._<Faithful>_._._._._._.")
    message(STATUS "+> Compilation has been started")
    message(STATUS "+> CMake Version: ${CMAKE_VERSION}")
    message(STATUS "+> CMake Generator: ${CMAKE_GENERATOR}")
    message(STATUS "+> System: ${CMAKE_SYSTEM}")
    message(STATUS "+> Build type: ${CMAKE_BUILD_TYPE}")
    message("")
endmacro(print_system_and_cmake_info)

macro(print_compiler_info)
    message(STATUS "+> C Compiler: ${CMAKE_C_COMPILER} ${CMAKE_C_COMPILER_VERSION}")
    message(STATUS "+> C Config: ${CMAKE_C_STANDARD}")
    message(STATUS "+> CMAKE_C_FLAGS: ${CMAKE_C_FLAGS}")
    message(STATUS "+> CXX Compiler: ${CMAKE_CXX_COMPILER} ${CMAKE_CXX_COMPILER_VERSION}")
    message(STATUS "+> CXX Standard: ${CMAKE_CXX_STANDARD}")
    message(STATUS "+> CMAKE_CXX_FLAGS: ${CMAKE_CXX_FLAGS}")
    message(STATUS "+> Extra options: ${FAITHFUL_COMPILE_OPTIONS}")
    message("")
endmacro(print_compiler_info)

macro(print_dir_info)
    message(STATUS "+> Source directory: ${FAITHFUL_SOURCE_DIR}")
    message(STATUS "+> Binary directory: ${FAITHFUL_BINARY_DIR}")
    message(STATUS "+> Install directory: ${FAITHFUL_INSTALL_DIR}")
    message("")
endmacro(print_dir_info)


function(print_option optName optVal)
    if(${optVal})
        message(STATUS "+> ${optName}  - ON")
    else()
        message(STATUS "+> ${optName}  - OFF")
    endif()
endfunction()

macro(print_build_options)
    print_option("AssetDownloader     " ${FAITHFUL_BUILD_ASSET_DOWNLOADER})
    print_option("AssetPack           " ${FAITHFUL_BUILD_ASSET_PACK})
    print_option("AssetProcessor      " ${FAITHFUL_BUILD_ASSET_PROCESSOR})
    print_option("Build tests         " ${FAITHFUL_BUILD_TESTS})
    print_option("Enable clang-tidy   " ${FAITHFUL_ENABLE_CLANG_TIDY})
    print_option("Run ASAN            " ${FAITHFUL_ASAN})
    print_option("Run TSAN            " ${FAITHFUL_TSAN})
    message("")
endmacro(print_build_options)
