
macro(print_system_and_cmake_info)
    message(STATUS "._._._._._._<Faithful>_._._._._._.")
    message(STATUS "+> Compilation has been started")
    message(STATUS "+> CMake Version: ${CMAKE_VERSION}")
    message(STATUS "+> CMake Generator: ${CMAKE_GENERATOR}")
    message(STATUS "+> System: ${CMAKE_SYSTEM}")
    message(STATUS "+> Build type: ${CMAKE_BUILD_TYPE}")
    message("")
endmacro(print_system_and_cmake_info)

macro(print_compiler_info)
    message(STATUS "+> C Compiler: ${CMAKE_C_COMPILER} ${CMAKE_C_COMPILER_VERSION}")
    message(STATUS "+> C Config: ${CMAKE_C_STANDARD}")
    message(STATUS "+> CMAKE_C_FLAGS: ${CMAKE_C_FLAGS}")
    message(STATUS "+> CXX Compiler: ${CMAKE_CXX_COMPILER} ${CMAKE_CXX_COMPILER_VERSION}")
    message(STATUS "+> CXX Standard: ${CMAKE_CXX_STANDARD}")
    message(STATUS "+> CMAKE_CXX_FLAGS: ${CMAKE_CXX_FLAGS}")
    message(STATUS "+> Extra options: ${FAITHFUL_COMPILE_OPTIONS}")
    message("")
endmacro(print_compiler_info)

macro(print_dir_info)
    message(STATUS "+> Source directory: ${FAITHFUL_SOURCE_DIR}")
    message(STATUS "+> Binary directory: ${FAITHFUL_BINARY_DIR}")
    message(STATUS "+> Install directory: ${FAITHFUL_INSTALL_DIR}")
    message("")
endmacro(print_dir_info)


function(print_option optName optVal)
    if(${optVal})
        message(STATUS "+> ${optName}  - ON")
    else()
        message(STATUS "+> ${optName}  - OFF")
    endif()
endfunction()

macro(print_build_options)
    print_option("AssetDownloader     " ${FAITHFUL_BUILD_ASSET_DOWNLOADER})
    print_option("AssetPack           " ${FAITHFUL_BUILD_ASSET_PACK})
    print_option("AssetProcessor      " ${FAITHFUL_BUILD_ASSET_PROCESSOR})
    print_option("Build tests         " ${FAITHFUL_BUILD_TESTS})
    print_option("Enable clang-tidy   " ${FAITHFUL_ENABLE_CLANG_TIDY})
    print_option("Build external      " ${FAITHFUL_BUILD_EXTERNAL})
    print_option("Build all externals " ${FAITHFUL_BUILD_EXTERNAL_ALL})
    print_option("Run ASAN            " ${FAITHFUL_ASAN})
    print_option("Run TSAN            " ${FAITHFUL_TSAN})
    message("")
endmacro(print_build_options)

function(print_not_found_externals)
    if(NOT GLFW_FOUND)
        message(WARNING "GLFW [glfw3 / glfw / libglfw] not found")
    endif()
    if(NOT GLM_FOUND)
        message(WARNING "GLM not found")
    endif()
    if(NOT GTEST_FOUND)
        message(WARNING "GTest not found")
    endif()
    if(NOT MIMALLOC_FOUND)
        message(WARNING "mimalloc not found")
    endif()
    if(NOT LIBOGG_FOUND)
        message(WARNING "ogg [ogg / libogg] not found")
    endif()
    if(NOT OPENAL_FOUND)
        message(WARNING "OpenAL(OpenAL-Soft) not found")
    endif()
    # OpenGL are required and if not found build cause FATAL in FindDeps.cmake
    if(NOT VORBIS_FOUND)
        message(WARNING "vorbis [vorbis / libvorbis] not found")
    endif()
    if(NOT VORBISENC_FOUND)
        message(WARNING "vorbisenc [vorbisenc / libvorbisenc] not found")
    endif()
    if(NOT VORBISFILE_FOUND)
        message(WARNING "vorbisfile [vorbisfile / libvorbisfile] not found")
    endif()
endfunction()
