
macro(print_system_and_cmake_info)
    message(STATUS "._._._._._._<Faithful>_._._._._._.")
    message(STATUS "+> Compilation has been started")
    message(STATUS "+> CMake Version: ${CMAKE_VERSION}")
    message(STATUS "+> CMake Generator: ${CMAKE_GENERATOR}")
    message(STATUS "+> System: ${CMAKE_SYSTEM}")
    message(STATUS "+> Build type: ${CMAKE_BUILD_TYPE}")
    message("")
endmacro(print_system_and_cmake_info)

macro(print_compiler_info)
    message(STATUS "+> C Compiler: ${CMAKE_C_COMPILER} ${CMAKE_C_COMPILER_VERSION}")
    message(STATUS "+> C Config: ${CMAKE_C_STANDARD}")
    message(STATUS "+> CMAKE_C_FLAGS: ${CMAKE_C_FLAGS}")
    message(STATUS "+> CXX Compiler: ${CMAKE_CXX_COMPILER} ${CMAKE_CXX_COMPILER_VERSION}")
    message(STATUS "+> CXX Standard: ${CMAKE_CXX_STANDARD}")
    message(STATUS "+> CMAKE_CXX_FLAGS: ${CMAKE_CXX_FLAGS}")
    message("")
endmacro(print_compiler_info)

macro(print_dir_info)
    message(STATUS "+> Source directory: ${CMAKE_SOURCE_DIR}")
    message(STATUS "+> Binary directory: ${CMAKE_BINARY_DIR}")
    message(STATUS "+> Install directory: ${FAITHFUL_INSTALL_DIR}")
    message("")
endmacro(print_dir_info)


function(printopt optName optVal)
    if(${optVal})
        message(STATUS "+> ${optName}  - ON")
    else()
        message(STATUS "+> ${optName}  - OFF")
    endif()
endfunction()

macro(print_build_options)
    printopt("AssetProcessor     " ${BUILD_ASSET_PROCESSOR})
    printopt("Download assets    " ${INIT_ASSETS})
    printopt("Build tests        " ${BUILD_TESTS})
    printopt("Build util tests   " ${BUILD_TESTS_UTILS})
    printopt("Build assets tests " ${BUILD_TESTS_ASSETS})
    printopt("build benchmarks   " ${BUILD_BENCHMARKS})

    printopt("log buffering      " ${FAITHFUL_LOGGER_BUFFERING})
    if (FAITHFUL_LOGGER_SEVERITY_ONLY_FATAL)
        printopt("logger: only fatal " ${FAITHFUL_LOGGER_SEVERITY_ONLY_FATAL})
    elseif(FAITHFUL_LOGGER_SEVERITY_NO_INFO)
        printopt("logger: no info    " ${FAITHFUL_LOGGER_SEVERITY_NO_INFO})
    else()
        message(STATUS "+> logger: all          - ON")
    endif()

    message("")
endmacro(print_build_options)

